SELECT DOCTOR.NAME, PROFESSOR.NAME, SINGER.NAME, ACTOR.NAME
FROM (
    SELECT NAME, ROWNUM AS NUM
    FROM (
        SELECT NAME
        FROM OCCUPATIONS
        WHERE OCCUPATION = 'Doctor'
        ORDER BY NAME
    ) 
) DOCTOR 
FULL OUTER JOIN 
(
    SELECT NAME, ROWNUM AS NUM
    FROM (
        SELECT NAME
        FROM OCCUPATIONS
        WHERE OCCUPATION = 'Professor'
        ORDER BY NAME
    ) 
) PROFESSOR 
ON PROFESSOR.NUM = DOCTOR.NUM
FULL OUTER JOIN 
(
    SELECT NAME, ROWNUM AS NUM
    FROM (
        SELECT NAME
        FROM OCCUPATIONS
        WHERE OCCUPATION = 'Singer'
        ORDER BY NAME
    ) 
) SINGER 
ON SINGER.NUM = PROFESSOR.NUM
FULL OUTER JOIN 
(
    SELECT NAME, ROWNUM AS NUM
    FROM (
        SELECT NAME
        FROM OCCUPATIONS
        WHERE OCCUPATION = 'Actor'
        ORDER BY NAME
    ) 
) ACTOR 
ON ACTOR.NUM = PROFESSOR.NUM
;